version: 2.1

command:
  print_pipeline_id:
    parameters:
      value:
        type: string
        default: "Could not get ENV variable"
    steps:
      - run: echo <<parameters.value>>

workflows:
  version: 2
  build:
    jobs:
      - print_pipeline
      - build

jobs:
  print_pipeline:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - print_pipeline_id:
          value: $CIRCLE_WORKFLOW_ID
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
